import "@/styles/globals.css";

import { type Metadata } from "next";
import { Fraunces, Space_Grotesk } from "next/font/google";

import { WagmiProviders } from "@/app/_components/wagmi-provider";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const displayFont = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
});

const bodyFont = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-body",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${displayFont.variable} ${bodyFont.variable}`}>
      <body>
        <WagmiProviders>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </WagmiProviders>
      </body>
    </html>
  );
}
