/**
 * Murmur Protocol - Common Types
 * Most types are now auto-generated by Prisma from schema.prisma
 * This file contains additional utility types
 */

// Re-export Prisma types
export {
  TopicStatus,
  VpAction,
  SettlementType,
  SettlementStatus,
} from "@prisma/client";

// API Response types
export interface TopicWithStatus {
  id: number;
  title: string;
  description: string;
  status: string;
  isFrozen: boolean;
  isExpired: boolean;
  messageCount: number;
  uniqueUsers: number;
  createdAt: Date;
}

export interface VpSettlement {
  users: string[];
  amounts: string[];
  nonce: number;
  signature: string;
}

export interface MintSignature {
  topicId: number;
  topicHash: string;
  curatedHash: string;
  refundUsers: string[];
  refundAmounts: string[];
  nonce: number;
  signature: string;
}
